name: Periodic Health Check
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  HealthCheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://full-stack-open-pokedex-crimson-leaf-8214.fly.dev/'
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
        #   cookie: token=asdf1234
        #   basic-auth: 'login:password'
